### ISSUE TITLE
Treinamento sobre Open Source

### ISSUE THREAD

**Issue by Joao-Pedro-Moura** [fga-eps-mds/2020-1-Grupo-5#12]
## Descrição

Passar para equipe o que é um projeto Open Source.

## Tarefas

- [x] Explicar o que é Open Source.
- [x] Documentação necessária a ser feita.

## Critério de aceitação

- [x] Começar a produzir as documentações necessárias.

**Comment by Joao-Pedro-Moura** [comment]
Treinamento feito no dia 01/09. Todos os integrantes compreenderam o conteúdo.

**Comment by RochaCarla** [comment]
Qual foi o conteúdo apresentado? onde está disponibilizado? 
Deixar as evidencias de execução no git/issues

**Comment by Joao-Pedro-Moura** [comment]
Foram utilizados estes links para apresentação do conteúdo:
- https://opensource.guide/
- https://opensource.guide/code-of-conduct/
- https://opensource.guide/starting-a-project/
