### ISSUE TITLE
Backlog Do Produto

### ISSUE THREAD

**Issue by Joaoaalves** [fga-eps-mds/2020-1-Grupo-5#16]
## Descrição

Criar backlog do nosso produto

## Tarefas

- [x] Listar principais funcionalidades
- [x] Estudar o risco de cada uma
- [x] Estudar a importância de cada uma

## Critério de aceitação

- [x] Definir a lista de prioridade de funcionalidades a serem implementadas(De acordo com risco e importância)

**Comment by Gabriel-Azevedo-Batalha** [comment]
A lista de prioridade das funcionalidades foi passada aos demais membros do grupo
