### ISSUE TITLE
Estudo dos tópicos 1 e 3 do doc. de visão 

### ISSUE THREAD

**Issue by k3vin-batista** [fga-eps-mds/2020-1-Grupo-5#19]
## Descrição

Estudo sobre o tópico 1 (Introdução) e tópico 3 (Descrição da Parte Envolvida e do Usuário) do documento de visão.

## Tarefas

- [x] Definir o escopo e o propósito 
- [x] Definir perfis de usuários
- [x] Pesquisar alternativas a concorrência 

## Critério de aceitação

- [ ] Elaborar uma prévia de cada tópico

**Comment by marcosadrianonery** [comment]
Para a descrição das partes envolvidas leva-se em consideração:

 - Resumo dos Envolvidos:
 - Resumo do Usuárioo:
 - Ambiente do Usuário:
 - Perfis dos Envolvidos:
 - Perfis do Usuário:
 - Principais Necessidades dos Usuário ou dos Envolvidos:
 - Alternativas e Concorrência:
