### ISSUE TITLE
Estudar documentos de visão

### ISSUE THREAD

**Issue by Joaoaalves** [fga-eps-mds/2020-1-Grupo-5#2]
# Tarefas
- [x] Entender a necessidade do documento de visão

- [x] Entender a visão de solução necessária para a construção do documento

- [x] Entender a estrutura do documento

# Critério de aceitação

- [x] Decidir template a ser utilizado

- [x] Definir parâmetros necessários para a criação do documento

**Comment by k3vin-batista** [comment]
Parâmetros necessários:
- Introdução 
- Posicionando
- Descrições da Parte Interessada e do Usuário
- Visão Geral do Produto
- Recursos do Produto
- Restrições
- Faixas de Qualidade
- Precedência e Prioridade
- Outros Requisitos do Produto
- Requisitos de Documentação
- Apêndice - Atributos do Recurso

Parâmetros setados pela IBM*
