### ISSUE TITLE
Construção da representação do produto e visão lógica

### ISSUE THREAD

**Issue by Joaoaalves** [fga-eps-mds/2020-1-Grupo-5#23]
## Descrição

Construir a representação do produto (Diagrama de relações, tecnologias, etc) e visão lógica no documento de arquitetura.

## Tarefas

- [x] Definir tecnologias
- [x] Definir pacotes

## Critério de aceitação

- [x] Construir tópico 2 (Representação de produto)
- [x] Construir tópico 4 (Visão lógica)

**Comment by Joaoaalves** [comment]
Tecnologias e arquitetura definidos no [documento de arquitetura](https://github.com/fga-eps-mds/2020-1-Grupo-5/blob/develop/docs/documents/documento-arquitetura.md).

**Comment by Joao-Pedro-Moura** [comment]
Prévia dos pacotes presentes no documento
