### ISSUE TITLE
Escrever a Introdução doc. de arquitetura

### ISSUE THREAD

**Issue by k3vin-batista** [fga-eps-mds/2020-1-Grupo-5#24]
## Descrição

Construção da introdução do documento de arquitetura

## Tarefas

- [x] Definir a finalidade 
- [x] Definir o escopo

## Critério de aceitação

- [x] Escrever a introdução

**Comment by k3vin-batista** [comment]
documento de arquitetura feito no projeto ADA para referência:
https://fga-eps-mds.github.io/2019.1-ADA/#/docs/project/architecture_doc

**Comment by marcosadrianonery** [comment]
Documento de arquitetura feito pelo grupo ArBC para referência:

https://github.com/fga-eps-mds/2019.2-ArBC/blob/develop/docs/mds/Documento_de_arquitetura.md
