### ISSUE TITLE
Criação das metas e restrições da arquitetura

### ISSUE THREAD

**Issue by Gabriel-Azevedo-Batalha** [fga-eps-mds/2020-1-Grupo-5#25]
## Descrição
Criação do tópico 3 (Metas e restrições da arquitetura) no documento de arquitetura

## Tarefas

- [x] Definir as metas do software
- [x] Definir as restrições da arquitetura

## Critério de aceitação

- [x] Construir o tópico 3 do documento de arquitetura

**Comment by lucas229** [comment]
Construção inicial do tópico concluída.
