### ISSUE TITLE
Escrever tópicos 1 e 2 do backlog 

### ISSUE THREAD

**Issue by k3vin-batista** [fga-eps-mds/2020-1-Grupo-5#26]
## Descrição

Construção dos tópicos 1 e 2 do documento de product backlog.

## Tarefas

- [x] Escrever Épicos
- [x] Escrever features

## Critério de aceitação

- [x] Escrever os tópicos 1 e 2

**Comment by k3vin-batista** [comment]
product backlog para referencia: 
1 - https://github.com/fga-eps-mds/2019.1-Aix/blob/master/docs/_posts/2019-04-05-backlog-de-produto.md
2 - https://fga-eps-mds.github.io/2019.1-ADA/#/docs/project/backlog

**Comment by marcosadrianonery** [comment]
Para referencia dos Epics:
1 - https://github.com/fga-eps-mds/2019.2-ArBC/blob/develop/docs/Product-Backlog.md/
2 - https://knowledge21.com.br/blog/product-backlog-epico-historia-tarefas/

**Comment by marcosadrianonery** [comment]
Alterações feitas no Backlog com relação aos Epics, passagem para o modelo apresentado em aula:
Anteriormente tinha-se a seguinte forma:
|Épicos|Descrição|
|:-----------------------------------------------------------------:|:-------------------------------------------:|
|EP1| Eu, enquanto usuário, gostaria de uma apresentação do produto.|
|EP2| Eu, enquanto usuário, desejo saber quais as permissões para instalação do bot.|
|EP3| Eu, enquanto usuário, gostaria de uma comunicação limpa.|
|EP4| Eu, enquanto usuário, gostaria de receber meus relatórios em uma dada frequência.|
|EP5| Eu, enquanto administrador, gostaria de ser capaz de alterar funcionalidades.|
|EP6| Eu, enquanto usuario, gostaria de me cadastrar.|

Passa a ter a seguinte forma:

|Épicos|Descrição|
|:-----------------------------------------------------------------:|:-------------------------------------------:|
|EP1| Apresentação do produto.|
|EP2| Instalação do bot.|
|EP3| Comunicação.|
|EP4| Relatórios.|
|EP5| Alterar funcionalidades.|
|EP6| Cadastro.|
