### ISSUE TITLE
Construção do tópico 3 do backlog do produto

### ISSUE THREAD

**Issue by Gabriel-Azevedo-Batalha** [fga-eps-mds/2020-1-Grupo-5#27]
## Descrição

Construção do tópico 3 (Histórias de usuário) do backlog do produto

## Tarefas

- [x] Elaborar as histórias de usuário

## Critério de aceitação

- [x] Escrever o tópico 3 do backlog do produto

**Comment by lucas229** [comment]
A dupla escreveu as Histórias de Usuário iniciais.
