### ISSUE TITLE
Estudar Documento de Arquitetura

### ISSUE THREAD

**Issue by Joaoaalves** [fga-eps-mds/2020-1-Grupo-5#3]
# Tarefas
- [x] Entender a necessidade deste.

- [x] Entender a construção do documento.

- [x] Entender todos os processos necessários para estarem documentados.

# Critérios de aceitação
- [x] Definir parâmetros necessários para a construção do documento

**Comment by marcosadrianonery** [comment]
O documento foi aberto no seguinte endereço:
https://github.com/fga-eps-mds/2020-1-Grupo-5/blob/master/docs/documents/documento-arquitetura.md

Parâmetros necessários:

1. Introdução
2. Representação da Arquitetura
3. Metas e Restrições Arquiteturais
4. Artefatos Arquiteturais
5. Qualidade

Bibliografia:
http://mds.cultura.gov.br/extend.formal_resources/guidances/examples/resources/sadoc_v1.htm

1 - Documentos passados levados em consideração:
1.1 - Por ser um tema parecido:
a - https://github.com/fga-eps-mds/2019.2-GloriaBot/blob/master/docs/DocumentoVisaoGloria.md
b - https://github.com/fga-eps-mds/2019.2-Chatbot-Nilo/blob/develop/docs/DocumentoDeArquitetura.md
c - https://github.com/ChatBot-Bino/Chatbot-Bino/tree/dev
1.2 - Melhor construido:
a - https://github.com/fga-eps-mds/2019.2-Acacia/blob/develop/docs/architecture_document.md
b - https://github.com/fga-eps-mds/2019.2-ArBC/blob/develop/docs/mds/Documento_de_arquitetura.md
