### ISSUE TITLE
Estudo sobre banco de dados MySQL

### ISSUE THREAD

**Issue by k3vin-batista** [fga-eps-mds/2020-1-Grupo-5#36]
## Descrição

Estudo sobre banco de dados relacionado ao uso da linguagem python que será usada no projeto

## Tarefas

- [x] Procurar por links em que seja possível aprender sobre o banco de dados
- [x] Compartilhar com a equipe os conhecimentos adquiridos

## Critério de aceitação

- [x] Equipe aprender a usar as principais funcionalidades

**Comment by Joaoaalves** [comment]
Connector: https://www.w3schools.com/python/python_mysql_getstarted.asp

Implementação: https://dev.mysql.com/doc/connector-python/en/

**Comment by Joaoaalves** [comment]
First Connection: https://dev.mysql.com/doc/connector-python/en/connector-python-example-connecting.html
