### ISSUE TITLE
Estudo de tecnologias open source

### ISSUE THREAD

**Issue by Joaoaalves** [fga-eps-mds/2020-1-Grupo-5#5]
# Tarefas

- [x] Entender o que é o open source

- [x] Entender como criar um projeto open source

- [x] Entender como integrar o projeto com outro software open source

# Critério de aceitação

- [x] Revisar e entender como aplicar os conceitos de open source no projeto

**Comment by Joao-Pedro-Moura** [comment]
O melhor local para saber o motivo de utilizar projetos Open Source foi no próprio guia presente no Github, pois lá tem diversas perguntas e respostas convenientes as nossas, como:
- O que é um projeto de Open Source?
- Por que realizar um projeto com código aberto?
- Como contribuir em um código aberto?
E várias outras perguntas que possamos vir a ter. 

Foi por esse guia que fundamentei meus estudos.

Segue o link: https://opensource.guide/
