### ISSUE TITLE
US07 - Eu, como usuário, desejo saber as funcionalidades do ChatBot

### ISSUE THREAD

**Issue by Gabriel-Azevedo-Batalha** [fga-eps-mds/2020-1-Grupo-5#56]
## Descrição

Permitir que o usuário possa se informar sobre as funcionalidades do DoctorS

## Tarefas

- [x] Disponibilizar uma lista de todas as funcionalidades
- [x] Informar o que cada funcionalidade faz
- [x] Adicionar informações sobre como navegar nos menus

## Critério de aceitação

- [x] Tutorial de funcionalidades implementado e funcionando corretamente

**Comment by Gabriel-Azevedo-Batalha** [comment]
Todas as funcionalidades atualmente presentes (ou em desenvolvimento) com exceção do próprio botão ajuda aparentemente estão listadas.

**Comment by lucas229** [comment]
Foram adicionadas algumas informações gerais sobre o processo de utilização do chatbot.
