### ISSUE TITLE
Planejamento de comunicação

### ISSUE THREAD

**Issue by Joaoaalves** [fga-eps-mds/2020-1-Grupo-5#6]
# Tarefas

- [x] Entender objetivos do projeto

- [x] Estudar o publico alvo da aplicação

- [x] Acordar melhores horários para a equipe trabalhar

# Critérios de aceitação

- [x] Definir horário e dia de reuniões

- [x] Definir melhores meios de comunicação

- [x] Definir cronograma da equipe

**Comment by Joaoaalves** [comment]
### Review:
Definido horário para reunião semanal para gestão de futura e atual sprints. Também foi feito um cronograma de horários livres de cada um para futuro cronograma de trabalho.

**Comment by marcosadrianonery** [comment]
link para o plano de comunicação: https://github.com/fga-eps-mds/2020-1-Grupo-5/blob/master/docs/documents/plano-comunicacao.md
