### ISSUE TITLE
US06 - Eu, como usuário, desejo receber dicas para cuidar da saúde

### ISSUE THREAD

**Issue by Gabriel-Azevedo-Batalha** [fga-eps-mds/2020-1-Grupo-5#62]
## Descrição

Permitir o usuário receber dicas para cuidar da saúde

## Tarefas

- [x] Criar uma lista de dicas
- [x] Disponibilizar as dicas ao usuário

## Critério de aceitação

- [x] Função de dica funcionando corretamente

**Comment by Gabriel-Azevedo-Batalha** [comment]
Fontes para as dicas:
- Ministério da Saúde
- App do Guardiões da Saúde

**Comment by lucas229** [comment]
O handler para as dicas foi adicionado na branch feature/health_tips. Os tópicos com as dicas já podem ser adicionados.

**Comment by Gabriel-Azevedo-Batalha** [comment]
Mais fontes:
- Secretaria de Estado de Segurança Pública
- BBC News
- Governo Federal
