### ISSUE TITLE
Criar página no Github Pages

### ISSUE THREAD

**Issue by lucas229** [fga-eps-mds/2020-1-Grupo-5#66]
## Descrição
Criar uma página no Github Pages para o colocar os documentos do repositório.

## Tarefas
- [x] Pesquisar como criar uma página no Github Pages
- [x] Criar a página
- [x] Adicionar os documentos

## Critério de aceitação
- [x] Página criada e funcionando corretamente

**Comment by lucas229** [comment]
Foi criada uma branch vazia para a página do Github Pages utilizando o seguinte tutorial: https://jiafulow.github.io/blog/2020/07/09/create-gh-pages-branch-in-existing-repo/

Documentação do Github Pages:
https://docs.github.com/pt/free-pro-team@latest/github/working-with-github-pages/getting-started-with-github-pages

**Comment by Gabriel-Azevedo-Batalha** [comment]
Foi adicionado o link para a página (Ainda sem nada) do Github Pages na descrição do repositório

**Comment by k3vin-batista** [comment]
Os documentos já estão na página
