### ISSUE TITLE
Bug na edição de perfil

### ISSUE THREAD

**Issue by lucas229** [fga-eps-mds/2020-1-Grupo-5#71]
### Descrição
O bot está permitindo que alterações de username, raça, gênero sexual e nascimento sejam aceitas mesmo que as entradas sejam inválidas. No caso do grupo de risco e trabalho, ao inserir uma entrada inválida, o dado não é alterado, porém o bot diz que foi alterado.

### Reprodução
Passos para reproduzir o erro:

1. Vá em Editar perfil
2. Selecione algum dado para alterar
3. Insira um dado inválido
4. A informação será alterada com uma entrada inválida ou a informação não será alterada, porém o bot envia mensagem dizendo que foi alterada

### Comportamento esperado
Informações inválidas não devem ser aceitas e não devem ser enviadas mensagens de informação alterada caso a entrada seja inválida.

**Comment by marcosadrianonery** [comment]
Os bugs foram corrigidos e as alterações podem serem encontradas na branch 'feature/send_messages_0.1'.
